import React from "react";
import { View, Text, StyleSheet, Image } from "react-native";

const AlertBox = () => {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Alert</Text>
      <View style={styles.content}>
        <Text style={styles.text}>
          The result generated by AI can have some errors, so do not completely rely on it.
        </Text>
        <Image source={require("../assets/images/alert.png")} style={styles.alertIcon} />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: "transparent", // No background color
    padding: 15,
    borderRadius: 10,
    marginVertical: 15,
    borderWidth: 1, // Add border
    borderColor: "black", // Black border color
    marginTop:20,
}
,
  title: {
    fontWeight: "bold",
    fontSize: 16,
  },
  content: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
  },
  text: {
    flex: 1,
    color: "#555",
  },
  alertIcon: {
    width: 50,
    height: 50,
    marginLeft: 10,
    marginTop:20,
  },
});

export default AlertBox;
