import React from "react";
import { View, Text, StyleSheet, Image } from "react-native";

const AlertBox = () => {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Alert</Text>
      <View style={styles.content}>
        <Text style={styles.text}>
          The result generated by AI can have some errors, so do not completely rely on it.
        </Text>
        <Image source={{ uri: "https://cdn-icons-png.flaticon.com/512/753/753345.png" }} style={styles.icon} />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: "#FEE2E2",
    padding: 15,
    borderRadius: 10,
    marginVertical: 15,
  },
  title: {
    fontWeight: "bold",
    fontSize: 16,
  },
  content: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
  },
  text: {
    flex: 1,
    color: "#555",
  },
  icon: {
    width: 30,
    height: 30,
    marginLeft: 10,
  },
});

export default AlertBox;
